### ISSUE TITLE
Prompts `No spell file downloaded for "programming" in utf-8` each startup

### ISSUE THREAD

**Issue by ok-nick** [psliwka/vim-dirtytalk#25] opened 2022-12-28 20:54 UTC
I'm using Neovim and each startup I get the prompt:
```
:!

No spell file for "programming" in utf-8
Download it?
(Y)es, [N]o:
```

Even after selecting `no`, `vim-dirtytalk` works perfectly. I can confirm the spell file is being downloaded to the correct path.

Here is my config, I'm using `lazy.nvim`:
```lua
return {
	"psliwka/vim-dirtytalk",
	build = function()
		vim.cmd("DirtytalkUpdate")
	end,
	init = function()
		vim.opt.spelllang:append("programming")
	end,
}
```

**Comment by dsully** [comment] 2023-01-06 19:42
I'm seeing the same thing.

**Comment by tapayne88** [comment] 2023-01-21 15:05
I found something similar with largely the same config after converting from packer.nvim to lazy.nvim. My error was the following when running `:setlocal spell`
```
Warning: Cannot find word list "programming.utf-8.spl" or "programming.ascii.spl"
```

I _think_ the issue is that lazy.nvim doesn't add "usual" paths to the neovim's `runtimepath`. It's kind of explained in the docs under [Startup Sequence](https://github.com/folke/lazy.nvim#%EF%B8%8F-startup-sequence).

I was able to resolve it by manually add the `site` location to the `runtimepath` - this is where vim-dirtytalk installs the lang file (`site/spell/programming-utf-8.spl`).

Now my config looks like this
```lua
return {
  'psliwka/vim-dirtytalk',
  build = ':DirtytalkUpdate',
  config = function()
    vim.opt.spelllang = { 'en', 'programming' }
    vim.opt.rtp:append(vim.fn.stdpath 'data' .. '/site')  -- Line of interest
  end,
}
```

Hope this helps!

**Comment by psliwka** [comment] 2024-02-09 20:28
I finally migrated to lazy.nvim and thus had a chance to test it, but I can't reproduce the issue above. I get a clean install without errors, even after manually purging all site files.

I'm going to assume that whatever the problem was, it's either fixed in the current lazy.nvim and/or neovim itself (I run v0.9.5). Please let me know if I'm wrong though! :pray:

**Closed by psliwka** 2024-02-09 20:28 UTC

**Comment by MartenBE** [comment] 2026-03-30 14:43
I am having a similar problem on 0.12:

- On init: `No spell file found for programming (utf-8). Download? [y/N]`
- If I then press `y`:

```
No spell file available for programming (utf8:curl: (22) The requested URL returned error: 404
 ascii:curl: (22) The requested URL returned error: 404
) — https://ftp.nluug.nl/pub/vim/runtime/spell/programming.utf-8.spl
Press ENTER or type command to continue
```

- If I then execute `:DirtytalkUpdate`:

```
Error in function dirtytalk#update:
line   10:
E117: Unknown function: spellfile#WritableSpellDir
line   11:
E121: Undefined variable: l:spell_dir
E116: Invalid arguments for function mkdir
line   12:
E121: Undefined variable: l:spell_dir
Press ENTER or type command to continue
```

My config:

```lua
return {
    "psliwka/vim-dirtytalk",
    build = ":DirtytalkUpdate",
    init = function()
        vim.opt.spelllang:append("programming")
    end,
}
```

I guess `DirtytalkUpdate` is broken and thus does not create the programming spell file?
