### ISSUE TITLE
Installation instructions confusion

### ISSUE THREAD

**Issue by farzadmf** [psliwka/vim-dirtytalk#1] opened 2022-04-26 02:00 UTC
Hi,

I copy/pasted the line for `vim-plug` from the `README`, but when I ran `PlugInstall`, it complained that `DirtytalkUpdate` is not a function.

After I installed and reloaded my config, I was able to manually run the function, so I was wondering if I missed something I needed to do

**Comment by psliwka** [comment] 2022-04-27 17:32
Unfortunately I could not reproduce it. Tested with clean Vim 8.2, vim-plug from current master, and .vimrc consisting only of:
```vim
call plug#begin()
Plug 'psliwka/vim-dirtytalk', { 'do': ':DirtytalkUpdate' }
call plug#end()
```

@farzadmf: could you please provide a minimal reproducible setup?

**Comment by farzadmf** [comment] 2022-04-27 21:36
I'm using with neovim so maybe that's why, I'll try to reproduce with a minimal config

**Comment by jordelver** [comment] 2022-05-01 10:16
ffiw I'm also having problems with Neovim.

My init.lua config:

```lua
Plug('psliwka/vim-dirtytalk', {['do'] = ':DirtytalkUpdate' })
```

When I do `:PlugInstall` I get this output:

```
x Post-update hook for vim-dirtytalk ... Vim(call):E117: Unknown function: dirtytalk#update
```

But if I run `:DirtytalkUpdate` after the plugin is installed everything seems to work.

Thanks for this plugin, great idea!

**Comment by heewa** [comment] 2022-06-17 19:09
Looks like this might caused by a change in neovim behavior, from this [vim-plug issue #11480](https://github.com/junegunn/vim-plug/issues/11480). I could get it to work with:

```vim
Plug 'psliwka/vim-dirtytalk', { 'do': ':let &rtp = &rtp \| DirtytalkUpdate' }
```

But hopefully this will soon be fixed in either neovim or vim-plug, so the workaround won't be necessary.

**Comment by psliwka** [comment] 2022-06-19 10:58
Thanks for identifying this, @heewa! Looks like it should be fixed with https://github.com/neovim/neovim/issues/18822.

**Closed** 2024-04-05 12:29 UTC
